"""empty message

Revision ID: 10f3abe865c7
Revises: ec3cf17a4d34
Create Date: 2026-03-27 08:52:47.235089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10f3abe865c7'
down_revision = 'ec3cf17a4d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
