"""empty message

Revision ID: b0d0a9dfc87d
Revises: 10f3abe865c7
Create Date: 2026-03-27 09:58:58.803414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0d0a9dfc87d'
down_revision = '10f3abe865c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('caption')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', mysql.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
