"""empty message

Revision ID: b283796b50ec
Revises: 13ea6173986e
Create Date: 2026-03-25 15:15:43.778976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b283796b50ec'
down_revision = '13ea6173986e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id_info', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('slogan', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_info')
    )
    op.create_table('info_stat',
    sa.Column('id_stat', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=55), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('info_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['info_id'], ['info.id_info'], ),
    sa.PrimaryKeyConstraint('id_stat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_stat')
    op.drop_table('info')
    # ### end Alembic commands ###
